name: Scalr

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - uses: buzzy/scalr-terraform-cli@v1
        with:
          terraform_version: '1.2.2'
          scalr_token: ${{ secrets.TERRAFORM_TOKEN }}
          scalr_hostname: 'daniele.scalr.io'
          scalr_environment: 'xxx'
          scalr_workspace: 'yyy'

      - name: Whereis
        run: whereis terraform

      - name: Version
        run: terraform -v

      - id: init
        run: terraform init

      - name: Print output
        run: echo ${{ steps.init.outputs.stdout }}
