name: Scalr

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - uses: Scalr/scalr-action@v1.5.0
        with:
          terraform_version: '1.2.1'
          scalr_token: ${{ secrets.TERRAFORM_TOKEN }}
          scalr_hostname: 'daniele.scalr.io'

      - name: Whereis scalr
        run: whereis scalr

      - name: Scalr-cli version
        run: scalr --version

      - run: env

      - name: Test run
        env:
          SCALR_TOKEN: ${{ secrets.TERRAFORM_TOKEN }}
          SCALR_HOSTNAME: 'daniele.scalr.io'
        run: scalr --verbose create-run

      - name: Whereis terraform
        run: whereis terraform

      - name: CLI Path
        run: ls -al $TERRAFORM_CLI_PATH

      - name: Version
        run: terraform -v
      
      - id: init
        run: terraform init

      - name: Print output
        run: echo '${{ steps.init.outputs.stdout }}'
